export const ACTION_TYPE = {
	SET_DEVICE_DATA: 'SET_DEVICE_DATA',
	RESET_DEVICE_DATA: 'RESET_DEVICE_DATA',
	ADD_TO_CART: 'ADD_TO_CART',
	DELETE_FROM_CART: 'DELETE_FROM_CART',
	AMOUNT_DEVICES: 'AMOUNT_DEVICES',
	SET_CART_DATA: 'SET_CART_DATA',
};
