export const ACTION_TYPE = {
	SET_DEVICE_DATA: 'SET_DEVICE_DATA',
	RESET_DEVICE_DATA: 'RESET_DEVICE_DATA',
	ADD_TO_CART: 'ADD_TO_CART',
	SWITCH_QUANTITY: 'SWITCH_QUANTITY',
	DELETE_FROM_CART: 'DELETE_FROM_CART',
	AMOUNT_DEVICES: 'AMOUNT_DEVICES',
	SET_CART_DATA: 'SET_CART_DATA',
	SET_USER: 'SET_USER',
	LOGOUT: 'LOGOUT',
	TOGGLE_CART: 'TOGGLE_CART',
	SET_CART_STORAGE: 'SET_CART_STORAGE',
	UPLOAD_CART_STORAGE: 'UPLOAD_CART_STORAGE',
};
